brew install font-3270-nerd-font
brew install font-abeezee
brew install font-abel
brew install font-aboriginal-sans
brew install font-aboriginal-serif
brew install font-abril-fatface
brew install font-aclonica
brew install font-acme
brew install font-actor
brew install font-adamina
brew install font-adinatha-tamil-brahmi
brew install font-advent-pro
brew install font-african-sans
brew install font-african-serif
brew install font-agave-nerd-font
brew install font-aguafina-script
brew install font-ahuramzda
brew install font-aileron
brew install font-akronim
brew install font-aladin
brew install font-aldrich
brew install font-alef
brew install font-alegreya-sans-sc
brew install font-alegreya-sans
brew install font-alegreya-sc
brew install font-alegreya
brew install font-aleo
brew install font-alex-brush
brew install font-alfa-slab-one
brew install font-alice
brew install font-alike-angular
brew install font-alike
brew install font-allan
brew install font-allerta-stencil
brew install font-allerta
brew install font-allura
brew install font-almendra-display
brew install font-almendra-sc
brew install font-almendra
brew install font-amarante
brew install font-amaranth
brew install font-amatic-sc
brew install font-amethysta
brew install font-amiri
brew install font-andada-sc
brew install font-andada
brew install font-andika
brew install font-angkor
brew install font-anka-coder
brew install font-annie-use-your-telescope
brew install font-anonymice-powerline
brew install font-anonymice-nerd-font
brew install font-anonymous-pro
brew install font-antic-didone
brew install font-antic-slab
brew install font-antic
brew install font-antinoou
brew install font-anton
brew install font-arapey
brew install font-arbutus-slab
brew install font-arbutus
brew install font-architects-daughter
brew install font-archivo-black
brew install font-archivo-narrow
brew install font-arimo-nerd-font
brew install font-arizonia
brew install font-armata
brew install font-artifika
brew install font-arvo
brew install font-asap
brew install font-asset
brew install font-astloch
brew install font-asul
brew install font-atomic-age
brew install font-aubrey
brew install font-audiowide
brew install font-aurulent-sans-mono-nerd-font
brew install font-autour-one
brew install font-average-sans
brew install font-average
brew install font-averia-gruesa-libre
brew install font-averia-libre
brew install font-averia-sans-libre
brew install font-averia-serif-libre
brew install font-awesome-terminal-fonts
brew install font-bad-script
brew install font-baloo
brew install font-balthazar
brew install font-baron
brew install font-basic
brew install font-battambang
brew install font-baumans
brew install font-bayon
brew install font-bebas-neue
brew install font-belgrano
brew install font-belleza
brew install font-benchnine
brew install font-bentham
brew install font-berkshire-swash
brew install font-bevan
brew install font-bigblue-terminal-nerd-font
brew install font-bigelow-rules
brew install font-bigshot-one
brew install font-bilbo-swash-caps
brew install font-bilbo
brew install font-bitstream-vera
brew install font-bitstream-vera-sans-mono-nerd-font
brew install font-bitter
brew install font-black-ops-one
brew install font-blokk-neue
brew install font-bokor
brew install font-bonbon
brew install font-boogaloo
brew install font-bowlby-one-sc
brew install font-bowlby-one
brew install font-brawler
brew install font-bree-serif
brew install font-bubblegum-sans
brew install font-bubbler-one
brew install font-buda
brew install font-buenard
brew install font-bukyvede-bold
brew install font-bukyvede-italic
brew install font-bukyvede-regular
brew install font-bungee
brew install font-butcherman
brew install font-butterfly-kids
brew install font-cabin-condensed
brew install font-cabin-sketch
brew install font-cabin
brew install font-caesar-dressing
brew install font-cagliostro
brew install font-calligraffitti
brew install font-cambo
brew install font-camingocode
brew install font-candal
brew install font-cantarell
brew install font-cantata-one
brew install font-cantora-one
brew install font-capriola
brew install font-cardo
brew install font-carme
brew install font-carrois-gothic-sc
brew install font-carrois-gothic
brew install font-carter-one
brew install font-cascadia-code
brew install font-caskaydia-cove-nerd-font
brew install font-caudex
brew install font-cedarville-cursive
brew install font-ceviche-one
brew install font-changa-one
brew install font-chango
brew install font-chapbook
brew install font-charis-sil
brew install font-chau-philomene-one
brew install font-chela-one
brew install font-chelsea-market
brew install font-chenla
brew install font-cherry-cream-soda
brew install font-cherry-swash
brew install font-chewy
brew install font-chicle
brew install font-chivo
brew install font-cinzel-decorative
brew install font-cinzel
brew install font-clear-sans
brew install font-clicker-script
brew install font-coda-caption
brew install font-coda
brew install font-code2002
brew install font-code-new-roman-nerd-font
brew install font-codystar
brew install font-combo
brew install font-comfortaa
brew install font-comic-neue
brew install font-coming-soon
brew install font-conakry
brew install font-concert-one
brew install font-condiment
brew install font-consolas-for-powerline
brew install font-constructium
brew install font-content
brew install font-contrail-one
brew install font-convergence
brew install font-cookie
brew install font-copse
brew install font-corben
brew install font-courgette
brew install font-courier-prime
brew install font-cousine-nerd-font
brew install font-coustard
brew install font-covered-by-your-grace
brew install font-crafty-girls
brew install font-creepster
brew install font-crete-round
brew install font-crimson-text
brew install font-croissant-one
brew install font-crushed
brew install font-cuprum
brew install font-cutive-mono
brew install font-cutive
brew install font-d2coding
brew install font-daddy-time-mono-nerd-font
brew install font-damion
brew install font-dancing-script
brew install font-dashicons
brew install font-dawning-of-a-new-day
brew install font-days-one
brew install font-dejavu-sans-mono-for-powerline
brew install font-dejavu-sans-mono-nerd-font
brew install font-delius-swash-caps
brew install font-delius-unicase
brew install font-delius
brew install font-della-respira
brew install font-denk-one
brew install font-devicons
brew install font-devonshire
brew install font-dhyana
brew install font-digohweli-old-do
brew install font-diplomata-sc
brew install font-diplomata
brew install font-domine
brew install font-donegal-one
brew install font-doppio-one
brew install font-dorsa
brew install font-dosis
brew install font-dr-sugiyama
brew install font-droid-sans-mono-for-powerline
brew install font-droid-sans-mono-nerd-font
brew install font-duru-sans
brew install font-dynalight
brew install font-eagle-lake
brew install font-eater
brew install font-eb-garamond
brew install font-economica
brew install font-edlo
brew install font-electrolize
brew install font-elsie-swash-caps
brew install font-elsie
brew install font-emblema-one
brew install font-emilys-candy
brew install font-engagement
brew install font-englebert
brew install font-enriqueta
brew install font-erica-one
brew install font-esteban
brew install font-et-book
brew install font-euphoria-script
brew install font-everson-mono
brew install font-ewert
brew install font-exo
brew install font-ezra-sil
brew install font-fairfax
brew install font-fantasque-sans-mono-nerd-font
brew install font-fanwood-text
brew install font-fascinate-inline
brew install font-fascinate
brew install font-faster-one
brew install font-fasthand
brew install font-fauna-one
brew install font-federant
brew install font-federo
brew install font-felipa
brew install font-fenix
brew install font-finger-paint
brew install font-fira-code-nerd-font
brew install font-fira-mono-for-powerline
brew install font-fira-mono-nerd-font
brew install font-fira-sans
brew install font-fjalla-one
brew install font-fjord-one
brew install font-flamenco
brew install font-flavors
brew install font-fondamento
brew install font-fontawesome
brew install font-fontdiner-swanky
brew install font-forum
brew install font-foundation-icons
brew install font-francois-one
brew install font-freckle-face
brew install font-fredericka-the-great
brew install font-fredoka-one
brew install font-fresca
brew install font-frijole
brew install font-fruktur
brew install font-fugaz-one
brew install font-gabriela
brew install font-gafata
brew install font-galdeano
brew install font-galindo
brew install font-gentium-basic
brew install font-gentium-book-basic
brew install font-gentium-plus
brew install font-geo
brew install font-geostar-fill
brew install font-geostar
brew install font-germania-one
brew install font-gfs-didot
brew install font-gfs-neohellenic
brew install font-gidole
brew install font-gilda-display
brew install font-give-you-glory
brew install font-glass-antiqua
brew install font-glegoo
brew install font-gloria-hallelujah
brew install font-gnu-unifont
brew install font-go-mono-nerd-font
brew install font-go
brew install font-goblin-one
brew install font-gochi-hand
brew install font-gorditas
brew install font-graduate
brew install font-grand-hotel
brew install font-gravitas-one
brew install font-great-vibes
brew install font-griffy
brew install font-gruppo
brew install font-gudea
brew install font-habibi
brew install font-hack-nerd-font
brew install font-halant
brew install font-hammersmith-one
brew install font-hanamina
brew install font-handlee
brew install font-hanuman
brew install font-happy-monkey
brew install font-hasklig
brew install font-hasklug-nerd-font
brew install font-headland-one
brew install font-henny-penny
brew install font-hermeneus-one
brew install font-hermit
brew install font-herr-von-muellerhoff
brew install font-hind
brew install font-holtwood-one-sc
brew install font-homemade-apple
brew install font-homenaje
brew install font-hurmit-nerd-font
brew install font-hyppolit
brew install font-iceberg
brew install font-iceland
brew install font-icomoon
brew install font-idealist-sans
brew install font-im-fell-double-pica-sc
brew install font-im-fell-double-pica
brew install font-im-fell-dw-pica-sc
brew install font-im-fell-dw-pica
brew install font-im-fell-english-sc
brew install font-im-fell-english
brew install font-im-fell-french-canon-sc
brew install font-im-fell-french-canon
brew install font-im-fell-great-primer-sc
brew install font-im-fell-great-primer
brew install font-imprima
brew install font-inconsolata-dz-for-powerline
brew install font-inconsolata-dz
brew install font-inconsolata-for-powerline
brew install font-inconsolata-g-for-powerline
brew install font-inconsolata-lgc-nerd-font
brew install font-inconsolata-nerd-font
brew install font-inconsolata-go-nerd-font
brew install font-inder
brew install font-indie-flower
brew install font-inika
brew install font-input
brew install font-ionicons
brew install font-iosevka-nerd-font
brew install font-iranian-sans
brew install font-iranian-serif
brew install font-irish-grover
brew install font-istok-web
brew install font-italiana
brew install font-italianno
brew install font-jaapokki
brew install font-jacques-francois-shadow
brew install font-jacques-francois
brew install font-jetbrains-mono-nerd-font
brew install font-jim-nightshade
brew install font-jockey-one
brew install font-jolly-lodger
brew install font-josefin-sans
brew install font-josefin-slab
brew install font-joti-one
brew install font-jsmath-cmbx10
brew install font-judson
brew install font-julee
brew install font-julius-sans-one
brew install font-junge
brew install font-junicode
brew install font-jura
brew install font-just-another-hand
brew install font-just-me-again-down-here
brew install font-kalam
brew install font-kameron
brew install font-kantumruy
brew install font-karla-tamil-inclined
brew install font-karla-tamil-upright
brew install font-karla
brew install font-karma
brew install font-kaushan-script
brew install font-kavoon
brew install font-kawkab-mono
brew install font-kayases
brew install font-kdam-thmor
brew install font-keania-one
brew install font-keep-calm
brew install font-kelly-slab
brew install font-kenia
brew install font-khand
brew install font-khmer
brew install font-kisiska
brew install font-kite-one
brew install font-knewave
brew install font-koruri
brew install font-kotta-one
brew install font-koulen
brew install font-kranky
brew install font-kreon
brew install font-kristi
brew install font-krona-one
brew install font-la-belle-aurore
brew install font-laila
brew install font-lalezar
brew install font-lancelot
brew install font-lateef
brew install font-latin-modern-math
brew install font-latin-modern
brew install font-lato
brew install font-league-gothic
brew install font-league-script
brew install font-league-spartan
brew install font-leckerli-one
brew install font-ledger
brew install font-lekton-nerd-font
brew install font-lemon
brew install font-liberation-mono-for-powerline
brew install font-liberation-sans
brew install font-libertinus
brew install font-libre-baskerville
brew install font-libre-caslon-text
brew install font-libre-franklin
brew install font-life-savers
brew install font-ligature-symbols
brew install font-lilita-one
brew install font-lily-script-one
brew install font-limelight
brew install font-linden-hill
brew install font-lobster-two
brew install font-lobster
brew install font-lohit-assamese
brew install font-lohit-bengali
brew install font-lohit-devanagari
brew install font-lohit-gujarati
brew install font-lohit-kannada
brew install font-lohit-malayalam
brew install font-lohit-marathi
brew install font-lohit-nepali
brew install font-lohit-oriya
brew install font-lohit-punjabi
brew install font-lohit-tamil-classical
brew install font-lohit-tamil
brew install font-lohit-telugu
brew install font-londrina-outline
brew install font-londrina-shadow
brew install font-londrina-sketch
brew install font-londrina-solid
brew install font-lora
brew install font-love-ya-like-a-sister
brew install font-loved-by-the-king
brew install font-lovers-quarrel
brew install font-luckiest-guy
brew install font-luculent
brew install font-lusitana
brew install font-lustria
brew install font-m-plus
brew install font-macondo-swash-caps
brew install font-macondo
brew install font-magra
brew install font-maiden-orange
brew install font-mako
brew install font-marcellus-sc
brew install font-marcellus
brew install font-marck-script
brew install font-margarine
brew install font-marko-one
brew install font-marmelad
brew install font-marta
brew install font-marvel
brew install font-masinahikan-dene
brew install font-masinahikan
brew install font-mate-sc
brew install font-mate
brew install font-material-icons
brew install font-materialdesignicons-webfont
brew install font-maven-pro
brew install font-mclaren
brew install font-meddon
brew install font-medievalsharp
brew install font-medula-one
brew install font-megrim
brew install font-meie-script
brew install font-menlo-for-powerline
brew install font-merienda-one
brew install font-merienda
brew install font-merriweather-sans
brew install font-merriweather
brew install font-meslo-lg-for-powerline
brew install font-meslo-lg-nerd-font
brew install font-metal-mania
brew install font-metal
brew install font-metamorphous
brew install font-metrophobic
brew install font-mfizz
brew install font-miao-unicode
brew install font-michroma
brew install font-migmix-1m
brew install font-migmix-1p
brew install font-migmix-2m
brew install font-migmix-2p
brew install font-migu-1c
brew install font-migu-1m
brew install font-migu-1p
brew install font-migu-2m
brew install font-milonga
brew install font-miltonian-tattoo
brew install font-miltonian
brew install font-miniver
brew install font-miss-fajardose
brew install font-modern-antiqua
brew install font-molengo
brew install font-molle
brew install font-monda
brew install font-monofett
brew install font-monofur-for-powerline
brew install font-monofur-nerd-font
brew install font-monoid-nerd-font
brew install font-monoisome
brew install font-mononoki-nerd-font
brew install font-monoton
brew install font-monsieur-la-doulaise
brew install font-montaga
brew install font-montez
brew install font-montserrat-alternates
brew install font-montserrat-subrayada
brew install font-montserrat
brew install font-moul
brew install font-moulpali
brew install font-mountains-of-christmas
brew install font-mouse-memoirs
brew install font-mplus-nerd-font
brew install font-mr-bedfort
brew install font-mr-dafoe
brew install font-mr-de-haviland
brew install font-mrs-saint-delafield
brew install font-mrs-sheppards
brew install font-mukti-narrow
brew install font-muli
brew install font-myrica
brew install font-myricam
brew install font-mystery-quest
brew install font-n-gage
brew install font-namdhinggo-sil
brew install font-nanumgothic
brew install font-nanumgothiccoding
brew install font-nanummyeongjo
brew install font-neucha
brew install font-neuton
brew install font-new-athena-unicode
brew install font-new-rocker
brew install font-news-cycle
brew install font-nexa
brew install font-niconne
brew install font-nika
brew install font-nixie-one
brew install font-nobile
brew install font-nokora
brew install font-norican
brew install font-norwester
brew install font-nosifer
brew install font-nothing-you-could-do
brew install font-noticia-text
brew install font-noto-color-emoji
brew install font-noto-emoji
brew install font-noto-kufi-arabic
brew install font-noto-mono
brew install font-noto-naskh-arabic
brew install font-noto-nastaliq-urdu
brew install font-noto-sans-armenian
brew install font-noto-sans-avestan
brew install font-noto-sans-balinese
brew install font-noto-sans-bamum
brew install font-noto-sans-batak
brew install font-noto-sans-bengali
brew install font-noto-sans-brahmi
brew install font-noto-sans-buginese
brew install font-noto-sans-buhid
brew install font-noto-sans-canadian-aboriginal
brew install font-noto-sans-carian
brew install font-noto-sans-cham
brew install font-noto-sans-cherokee
brew install font-noto-sans-cjk-jp
brew install font-noto-sans-cjk-kr
brew install font-noto-sans-cjk-sc
brew install font-noto-sans-cjk-tc
brew install font-noto-sans-cjk
brew install font-noto-sans-coptic
brew install font-noto-sans-cuneiform
brew install font-noto-sans-cypriot
brew install font-noto-sans-deseret
brew install font-noto-sans-devanagari
brew install font-noto-sans-egyptian-hieroglyphs
brew install font-noto-sans-ethiopic
brew install font-noto-sans-georgian
brew install font-noto-sans-glagolitic
brew install font-noto-sans-gothic
brew install font-noto-sans-gujarati
brew install font-noto-sans-gurmukhi
brew install font-noto-sans-hanunoo
brew install font-noto-sans-imperial-aramaic
brew install font-noto-sans-inscriptional-pahlavi
brew install font-noto-sans-inscriptional-parthian
brew install font-noto-sans-javanese
brew install font-noto-sans-kaithi
brew install font-noto-sans-kannada
brew install font-noto-sans-kayah-li
brew install font-noto-sans-kharoshthi
brew install font-noto-sans-khmer
brew install font-noto-sans-lao
brew install font-noto-sans-lepcha
brew install font-noto-sans-limbu
brew install font-noto-sans-linear-b
brew install font-noto-sans-lisu
brew install font-noto-sans-lycian
brew install font-noto-sans-lydian
brew install font-noto-sans-malayalam
brew install font-noto-sans-mandaic
brew install font-noto-sans-meetei-mayek
brew install font-noto-sans-mongolian
brew install font-noto-sans-myanmar
brew install font-noto-sans-n-ko
brew install font-noto-sans-new-tai-lue
brew install font-noto-sans-ogham
brew install font-noto-sans-ol-chiki
brew install font-noto-sans-old-italic
brew install font-noto-sans-old-persian
brew install font-noto-sans-old-south-arabian
brew install font-noto-sans-old-turkic
brew install font-noto-sans-oriya
brew install font-noto-sans-osmanya
brew install font-noto-sans-phags-pa
brew install font-noto-sans-phoenician
brew install font-noto-sans-rejang
brew install font-noto-sans-runic
brew install font-noto-sans-samaritan
brew install font-noto-sans-saurashtra
brew install font-noto-sans-shavian
brew install font-noto-sans-sinhala
brew install font-noto-sans-sundanese
brew install font-noto-sans-syloti-nagri
brew install font-noto-sans-symbols
brew install font-noto-sans-syriac-eastern
brew install font-noto-sans-syriac-estrangela
brew install font-noto-sans-syriac-western
brew install font-noto-sans-tagalog
brew install font-noto-sans-tagbanwa
brew install font-noto-sans-tai-le
brew install font-noto-sans-tai-tham
brew install font-noto-sans-tai-viet
brew install font-noto-sans-tamil
brew install font-noto-sans-telugu
brew install font-noto-sans-thaana
brew install font-noto-sans-thai
brew install font-noto-sans-tibetan
brew install font-noto-sans-tifinagh
brew install font-noto-sans-ugaritic
brew install font-noto-sans-vai
brew install font-noto-sans-yi
brew install font-noto-sans
brew install font-noto-serif-armenian
brew install font-noto-serif-georgian
brew install font-noto-serif-khmer
brew install font-noto-serif-lao
brew install font-noto-serif-thai
brew install font-noto-serif
brew install font-noto-nerd-font
brew install font-nova-cut
brew install font-nova-flat
brew install font-nova-mono
brew install font-nova-oval
brew install font-nova-round
brew install font-nova-script
brew install font-nova-slim
brew install font-nova-square
brew install font-numans
brew install font-nunito
brew install font-nyashi
brew install font-ocra
brew install font-octicons
brew install font-odor-mean-chey
brew install font-office-code-pro
brew install font-offside
brew install font-old-standard-tt
brew install font-oldenburg
brew install font-oleo-script-swash-caps
brew install font-oleo-script
brew install font-open-iconic
brew install font-open-sans-condensed
brew install font-open-sans
brew install font-oranienbaum
brew install font-orbitron
brew install font-oregano
brew install font-orienta
brew install font-original-surfer
brew install font-oskiblackfoot
brew install font-oskidakelh
brew install font-oskidenea
brew install font-oskideneb
brew install font-oskidenec
brew install font-oskidenes
brew install font-oskieast
brew install font-oskiwest
brew install font-oswald
brew install font-over-the-rainbow
brew install font-overlock-sc
brew install font-overlock
brew install font-overpass-nerd-font
brew install font-ovo
brew install font-oxygen-mono
brew install font-oxygen
brew install font-pacifico
brew install font-padauk
brew install font-palemonas
brew install font-paprika
brew install font-parastoo
brew install font-parisienne
brew install font-passero-one
brew install font-passion-one
brew install font-pathway-gothic-one
brew install font-patrick-hand-sc
brew install font-patrick-hand
brew install font-patua-one
brew install font-paytone-one
brew install font-pecita
brew install font-peralta
brew install font-permanent-marker
brew install font-petit-formal-script
brew install font-petrona
brew install font-phetsarath
brew install font-philosopher
brew install font-piedra
brew install font-pinyon-script
brew install font-pirata-one
brew install font-pitabek
brew install font-plaster
brew install font-play
brew install font-playball
brew install font-playfair-display-sc
brew install font-playfair-display
brew install font-podkova
brew install font-poetsenone
brew install font-poiret-one
brew install font-poller-one
brew install font-poly
brew install font-pompiere
brew install font-pontano-sans
brew install font-poppins
brew install font-port-lligat-sans
brew install font-port-lligat-slab
brew install font-prata
brew install font-preahvihear
brew install font-prime
brew install font-prince-valiant
brew install font-princess-sofia
brew install font-prociono
brew install font-profont-nerd-font
brew install font-profontx
brew install font-prosto-one
brew install font-pt-mono
brew install font-pt-sans
brew install font-pt-serif
brew install font-puritan
brew install font-purple-purse
brew install font-qataban
brew install font-quando
brew install font-quantico
brew install font-quattrocento-sans
brew install font-quattrocento
brew install font-questrial
brew install font-quicksand
brew install font-quintessential
brew install font-quivira
brew install font-qwigley
brew install font-racing-sans-one
brew install font-radley
brew install font-rajdhani
brew install font-raleway-dots
brew install font-raleway
brew install font-rambla
brew install font-rammetto-one
brew install font-ranchers
brew install font-rancho
brew install font-rationale
brew install font-redacted
brew install font-redressed
brew install font-reenie-beanie
brew install font-revalia
brew install font-ribeye-marrow
brew install font-ribeye
brew install font-ricty-diminished
brew install font-righteous
brew install font-risque
brew install font-roboto-condensed
brew install font-roboto-mono-for-powerline
brew install font-roboto-mono-nerd-font
brew install font-roboto-slab
brew install font-roboto
brew install font-rochester
brew install font-rock-salt
brew install font-rokkitt
brew install font-romanesco
brew install font-ropa-sans
brew install font-rosario
brew install font-rosarivo
brew install font-rotinonhsonni-sans
brew install font-rotinonhsonni-serif
brew install font-rouge-script
brew install font-rounded-m-plus
brew install font-rozha-one
brew install font-ruda
brew install font-rufina
brew install font-ruge-boogie
brew install font-ruluko
brew install font-rum-raisin
brew install font-rupakara
brew install font-ruslan-display
brew install font-russo-one
brew install font-ruthie
brew install font-rye
brew install font-sacramento
brew install font-sadagolthina
brew install font-sail
brew install font-salsa
brew install font-samim
brew install font-sanchez
brew install font-sancreek
brew install font-sansita-one
brew install font-sarina
brew install font-sarpanch
brew install font-satisfy
brew install font-sauce-code-pro-nerd-font
brew install font-scada
brew install font-scheherazade
brew install font-schoolbell
brew install font-seaweed-script
brew install font-sevillana
brew install font-seymour-one
brew install font-shabnam
brew install font-shadows-into-light-two
brew install font-shadows-into-light
brew install font-shanti
brew install font-share-tech-mono
brew install font-share-tech
brew install font-share
brew install font-shojumaru
brew install font-short-stack
brew install font-shure-tech-mono-nerd-font
brew install font-siemreap
brew install font-sigmar-one
brew install font-signika-negative
brew install font-silent-lips
brew install font-simonetta
brew install font-sinkin-sans
brew install font-sintony
brew install font-sirin-stencil
brew install font-six-caps
brew install font-skranji
brew install font-slackey
brew install font-smokum
brew install font-smythe
brew install font-sniglet
brew install font-snippet
brew install font-snowburst-one
brew install font-sofadi-one
brew install font-sofia
brew install font-sonsie-one
brew install font-sorts-mill-goudy
brew install font-source-code-pro-for-powerline
brew install font-source-code-pro
brew install font-source-han-code-jp
brew install font-source-han-sans
brew install font-source-sans-pro
brew install font-source-serif-pro
brew install font-space-mono-nerd-font
brew install font-special-elite
brew install font-spicy-rice
brew install font-spinnaker
brew install font-spirax
brew install font-squada-one
brew install font-stalemate
brew install font-stalinist-one
brew install font-stardos-stencil
brew install font-stint-ultra-condensed
brew install font-stint-ultra-expanded
brew install font-stoke
brew install font-strait
brew install font-sue-ellen-francisco
brew install font-sunshiney
brew install font-supermercado-one
brew install font-swanky-and-moo-moo
brew install font-symbola
brew install font-syncopate
brew install font-tai-le-valentinium
brew install font-takaoex
brew install font-tangerine
brew install font-taprom
brew install font-tauri
brew install font-teko
brew install font-telex
brew install font-tenor-sans
brew install font-terminess-nerd-font
brew install font-terminus
brew install font-tex-gyre-adventor
brew install font-tex-gyre-bonum
brew install font-tex-gyre-chorus
brew install font-tex-gyre-cursor
brew install font-tex-gyre-heros
brew install font-tex-gyre-pagella-math
brew install font-tex-gyre-pagella
brew install font-tex-gyre-schola
brew install font-tex-gyre-termes
brew install font-text-me-one
brew install font-thabit
brew install font-the-girl-next-door
brew install font-tibetan-machine-uni
brew install font-tienne
brew install font-tillana
brew install font-tinos-nerd-font
brew install font-titan-one
brew install font-titillium-web
brew install font-trade-winds
brew install font-trocchi
brew install font-trochut
brew install font-trykker
brew install font-tuffy
brew install font-tulpen-one
brew install font-twitter-color-emoji
brew install font-ubuntu-mono-nerd-font
brew install font-ubuntu-nerd-font
brew install font-ultra
brew install font-uncial-antiqua
brew install font-underdog
brew install font-unica-one
brew install font-unifrakturcook
brew install font-unifrakturmaguntia
brew install font-unkempt
brew install font-unlock
brew install font-unna
brew install font-vampiro-one
brew install font-varela-round
brew install font-varela
brew install font-vast-shadow
brew install font-vazir-code
brew install font-vazir
brew install font-vibur
brew install font-victor-mono-nerd-font
brew install font-vidaloka
brew install font-viga
brew install font-voces
brew install font-vollkorn
brew install font-voltaire
brew install font-vt323
brew install font-waiting-for-the-sunrise
brew install font-wakor
brew install font-wallpoet
brew install font-walter-turncoat
brew install font-waltograph
brew install font-warnes
brew install font-wellfleet
brew install font-wendy-one
brew install font-wire-one
brew install font-work-sans
brew install font-xits
brew install font-yanone-kaffeesatz
brew install font-yellowtail
brew install font-yeseva-one
brew install font-yesteryear
brew install font-zeyada
